version: '3'
services:
  app1:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 50:3000
    working_dir: /app
#    volumes:
#      - ./app1/:/app
    environment:
      MYSQL_HOST: mysql1
      MYSQL_USER: root
      MYSQL_PASSWORD: secret1
      MYSQL_DB: todos
    networks:
      - app_network

  app2:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 60:3000
    working_dir: /app
#    volumes:
#      - ./app2/:/app
    environment:
      MYSQL_HOST: mysql1
      MYSQL_USER: root
      MYSQL_PASSWORD: secret1
      MYSQL_DB: todos
    networks:
      - app_network

      
  mysql1:
    image: mysql:8.0
    volumes:
      - todo-mysql-data1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret1
      MYSQL_DATABASE: todos
    networks:
      - app_network

  # mysql2:
  #   image: mysql:8.0
  #   volumes:
  #     - todo-mysql-data2:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret2
  #     MYSQL_DATABASE: todos
  #   networks:
  #     - app_network

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - app1 
      - app2
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app_network

networks:
  app_network:

volumes:
  todo-mysql-data1:
  # todo-mysql-data2:
